import { Avatar, Grid, Stack, Typography } from "@mui/material";
import { Box, Container } from "@mui/system";
import React from "react";
import Bk from "../../assets/blogAssests/bkk.jpg";

const Blog = () => {
  return (
    <Container>
      <Box sx={{ pt: "25px", color: "teal" }}>
        <Typography variant="h3" bgcolor="grey" color="white">
          BLOGS
        </Typography>
      </Box>
      <Box sx={{ mt: "50px" }}>
        <Grid container spacing={3}>
          <Grid item xs={8}>
            <Typography variant="h5" color="white" bgcolor="teal">
              Smarter Customer Engagement Flows with Courier’s New Segment.
            </Typography>
            <Stack direction="row" spacing={2} m="15px">
              <Avatar alt="Remy Sharp" src={Bk} />
              <Typography variant="p" m="10px">
                Author:
              </Typography>
              <Typography>Bachan Kubi</Typography>
            </Stack>

            <Box sx={{ border: 1, p: "15px", boxShadow: 0, borderRadius: 1 }}>
              <Typography variant="p" align="justify">
                Having a clear idea how your users interact with your app — when
                they log in, which features they engage with, or which
                notifications they click on — can help you design a better
                experience and ultimately increase user engagement. But
                retracing your users’ steps across various integrations is a
                complex task. Customer data platforms (CDPs) like Segment seek
                to achieve it by aggregating event data from multiple sources in
                one centralized location. <br />
                <br /> This helps businesses gain a clearer picture of their
                users, and use that insight to individualize the app experience.
                How an app communicates with its users is key. Whether you’re
                using web and mobile push notifications, an in-app inbox,
                automated email and SMS messages, or Slack notifications: all of
                that can have a huge impact on how the app experience is
                perceived by your users. That’s why it’s so vital to track
                notification usage data in your CDP. Today, we’re excited to
                announce that teams using Segment can now ingest notification
                usage data from Courier, so that it can serve as a basis for new
                insights. Which communications were successfully delivered?
                Which ones were opened and read? On what channels? These types
                of events generated in Courier can now be used to create custom
                user journeys. <br />
                <br /> This step completes the integration of the two services:
                previously, Segment was available as a data destination in
                Courier. Now that the integration has come full circle, let’s
                have a look at how your organization can benefit from combining
                the two tools. Marrying Courier and Segment In case you haven’t
                heard of us before, Courier is a notification platform that lets
                you develop, scale and manage multi-channel notifications for
                your application. Combining powerful API primitives with a
                no-code UI for designing and monitoring notification flows,
                Courier makes it far easier to build notification experiences
                that work in sync with your application UX than if you created a
                complex notification infrastructure from scratch. Segment is a
                popular customer data platform (CDP) that lets you collect data
                generated by your users in various locations and assemble it in
                one place. This gives you a more complete picture of your users,
                allowing you to target them in a smarter and more personalized
                way. <br />
                <br /> If your organization uses different tools to track and
                store user interactions, then you’re likely using a CDP like
                Segment. In Segment, your users’ interactions are stored as
                “events,” complete with metadata that you define in advance.
                Events can be associated with a user’s ID, or be stored
                anonymously, depending on permissions. You can then retrieve
                them for further data analysis, like aggregating and
                partitioning events according to different criteria, depending
                on the questions you’re trying to answer. For instance, you
                could be looking at general user engagement with a specific
                notification, announcing a new product feature. Or you could use
                your event data to understand how a specific group of people —
                for instance, 25- to 35-year-olds located in Southern Africa —
                engaged with your notification within a particular timespan;
                say, within 24 hours of sending the notification. Such
                information can now easily be obtained, thanks to the two-way
                integration of Courier and Segment. Test From Mehedi Hasan
              </Typography>
            </Box>
          </Grid>

          <Grid item xs={4}>
            <Typography variant="h6" color="white" bgcolor="teal">
              The Benefits of Outsourcing Courier Services for Retailers
            </Typography>
            <Stack direction="row" spacing={2} p="15px">
              <Avatar alt="Remy Sharp" src="/static/images/avatar/1.jpg" />
              <Typography>Mehedi Hasan</Typography>
            </Stack>
            <Typography sx={{ p: "10px" }}>
              If you’re like most business owners, you are always looking for
              ways to save time and energy. That’s why outsourcing your courier
              services can be so beneficial for retailers. When you partner with
              a professional courier company, they will handle all of your
              warehousing and shipping needs, allowing you to focus on running
              your store. There are many benefits of outsourcing courier
              services, including cost savings, convenience, and time savings.
              In this blog post, we will discuss the top benefits of using a
              professional courier service for your retail business. <br />
              <br />
              While you focus on running your business, a professional courier
              can handle all of your warehousing and shipping needs. There are
              many advantages of outsourcing courier services for retailers
              that................................
            </Typography>
          </Grid>
        </Grid>
      </Box>
    </Container>
  );
};

export default Blog;
